//
//  ConstantVariables.m
//  ST
//
//  Created by 李晓春 on 15/4/7.
//  Copyright (c) 2015年 Teng Niu. All rights reserved.
//

#import "ConstantVariables.h"

const NSString *IS_USER_HAS_SETTING = @"IS_USER_HAS_SETTING";
const NSString *USER_SETTING_COUNT = @"USER_SETTING_COUNT";
const NSString *USER_SETTING_WORKING = @"USER_SETTING_WORKING";
const NSString *USER_SETTING_REST = @"USER_SETTING_REST";
const NSString *USER_SETTING_WORK_STEP_COUNT = @"USER_SETTING_WORK_STEP_COUNT";
const NSString *USER_SETTING_WORK_STEP = @"USER_SETTING_WORK_STEP";
const NSString *USER_SETTING_REST_STEP_COUNT = @"USER_SETTING_REST_STEP_COUNT";
const NSString *USER_SETTING_REST_STEP = @"USER_SETTING_REST_STEP";


const NSString *USER_SUCCESS_COUNT = @"USER_SUCCESS_COUNT";
const NSInteger USER_SUCCESS_AD_COUNT = 10;


